<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Service extends \App\Entity\Service implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'service_name', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'service_label', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'serviceResponseKeys', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'serviceRequests'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'service_name', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'service_label', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'serviceResponseKeys', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'serviceRequests'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Service $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceName', []);

        return parent::getServiceName();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceName(string $service_name): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceName', [$service_name]);

        return parent::setServiceName($service_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceLabel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceLabel', []);

        return parent::getServiceLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceLabel(string $service_label): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceLabel', [$service_label]);

        return parent::setServiceLabel($service_label);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): ?\App\Entity\Category
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(?\App\Entity\Category $category): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceResponseKeys(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceResponseKeys', []);

        return parent::getServiceResponseKeys();
    }

    /**
     * {@inheritDoc}
     */
    public function addServiceResponseKey(\App\Entity\ServiceResponseKey $serviceResponseKey): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addServiceResponseKey', [$serviceResponseKey]);

        return parent::addServiceResponseKey($serviceResponseKey);
    }

    /**
     * {@inheritDoc}
     */
    public function removeServiceResponseKey(\App\Entity\ServiceResponseKey $serviceResponseKey): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeServiceResponseKey', [$serviceResponseKey]);

        return parent::removeServiceResponseKey($serviceResponseKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceRequests(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceRequests', []);

        return parent::getServiceRequests();
    }

    /**
     * {@inheritDoc}
     */
    public function addServiceRequest(\App\Entity\ServiceRequest $serviceRequest): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addServiceRequest', [$serviceRequest]);

        return parent::addServiceRequest($serviceRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function removeServiceRequest(\App\Entity\ServiceRequest $serviceRequest): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeServiceRequest', [$serviceRequest]);

        return parent::removeServiceRequest($serviceRequest);
    }

}
